const API_BASE_URL = "http://localhost:5062/api";

const API_ENDPOINTS = {
  login: `${API_BASE_URL}/User/login`,
  forgotPassword: `${API_BASE_URL}/User/forgot-password`,
  register: `${API_BASE_URL}/User/register`,
  resetPassword: `${API_BASE_URL}/User/reset-password`,
  verifyRegisterOtp: `${API_BASE_URL}/User/verifyotp`,
  verifyUpdateOtp: `${API_BASE_URL}/Otp/verify-and-update`,
  getDevicesID: (userId) => `${API_BASE_URL}/Devices/get-devices/${userId}`,
  getDailyMedicalData: (date, deviceId) => `${API_BASE_URL}/UserMedicalDatas/daily/${date}/${deviceId}`,
  getAverageLast14Days: (deviceId) => `${API_BASE_URL}/UserMedicalDatas/average-last-14-days/${deviceId}`,
  createAdmin: `${API_BASE_URL}/admin/create-admin`,
  changePassword: `${API_BASE_URL}/User/change-password`,
  deleteDevice: (deviceId) => `${API_BASE_URL}/devices/delete-device/${deviceId}`,
  addDevice: `${API_BASE_URL}/devices/add-device`,
  getDevices: (userId) => `${API_BASE_URL}/Devices/get-devices/${userId}`,
  updateBasicInfo: `${API_BASE_URL}/User/update-basic-info`,
  sendOtp: `${API_BASE_URL}/Otp/send-otp`,  
  createInvitation: (userId) => `${API_BASE_URL}/Invitation/create-invitation?userId=${userId}`,
  getRelationship: (userId) => `${API_BASE_URL}/Invitation/get-relationship?userId=${userId}`,
  useInvitation: `${API_BASE_URL}/Invitation/use-invitation`,
  deleteRelationship: (id) => `${API_BASE_URL}/Invitation/delete-relationship/${id}`,
  getUsers: `${API_BASE_URL}/admin/users`,
  addAdminRole: `${API_BASE_URL}/admin/add-admin-role`,
  removeAdmin: (userId) => `${API_BASE_URL}/admin/remove-admin/${userId}`, 
  getUserGps: (inviterId) => `${API_BASE_URL}/User/user-gps?userId=${inviterId}`,
  getPercentIndicatorIsTrue: (userId) => `${API_BASE_URL}/Indicators/get-percent-indicator-is-true?userId=${userId}`,
  getAverageDailyNightLast14Days: (deviceId) => `${API_BASE_URL}/UserMedicalDatas/average-daily-night-last-14-days/${deviceId}`,
  addDoctorRole: (userId) => `${API_BASE_URL}/admin/add-doctor-role/${userId}`,
  removeDoctorRole: (userId) => `${API_BASE_URL}/admin/remove-doctor-role/${userId}`,
  GetPercentIndicatorIsTrue: (userId) => `${API_BASE_URL}/Indicators/get-percent-indicator-is-true/${userId}`,
  addClinicalIndicator: `${API_BASE_URL}/Indicators/add-clinical-indicator`, 
  addMolecularIndicator: `${API_BASE_URL}/Indicators/add-molecular-indicator`,
  addSubclinicalIndicator: `${API_BASE_URL}/Indicators/add-subclinical-Indicator`,
  getUserDetails: `${API_BASE_URL}/Users/details`,
  updateUser: `${API_BASE_URL}/Users/update`,
  toggleAccountStatus: `${API_BASE_URL}/admin/toggle-account-status`,
  getHealthProfile: `${API_BASE_URL}/User/health-profile`,
  getDoctorDashboard: `${API_BASE_URL}/Doctor/dashboard`,
  getDoctorPatients: `${API_BASE_URL}/Doctor/my-patients`,
  getPatientSummary: (patientId) => `${API_BASE_URL}/Doctor/patient/${patientId}/summary`,
  getPatientAnomalies: (patientId) => `${API_BASE_URL}/Doctor/patient/${patientId}/anomalies`,
  getHealthRecords: `${API_BASE_URL}/User/health-records`,
  getHealthRecordsMetric: (metric) => `${API_BASE_URL}/User/health-records/metric/${metric}`,
  getUserDevices: `${API_BASE_URL}/User/devices`,
  getMyDoctors: `${API_BASE_URL}/user/my-doctors`,
  useInvitationCode: `${API_BASE_URL}/user/use-invitation-code`,
  getDoctorPatientsSearch: (query) => `${API_BASE_URL}/doctor/patients/search?query=${query}`,
  getMyPatientsSearch: (query) => `${API_BASE_URL}/doctor/my-patients/search?query=${query}`,
  checkPatientAccess: (patientId) => `${API_BASE_URL}/doctor/check-patient-access/${patientId}`,
  getUsersByRole: (role) => `${API_BASE_URL}/admin/users/by-role/${role}`,
  deleteUser: (userId) => `${API_BASE_URL}/admin/delete-user/${userId}`,
  getDoctorPatientsByDoctor: (doctorId) => `${API_BASE_URL}/admin/doctor-patients/${doctorId}`,
  getRelationships: (type) => `${API_BASE_URL}/admin/relationships?type=${type}`,
};

export default API_ENDPOINTS;